(* Reaching Definitions Analysis - Forward May-Analysis
 *
 * A definition d of variable v "reaches" a program point p if there is a
 * path from d to p along which v is not redefined. This is a FORWARD
 * analysis because information flows from definitions (earlier in the
 * program) forward to later points.
 *
 * Transfer function (applied forward):
 *   OUT[B] = gen[B] U (IN[B] - kill[B])
 *
 * Merge (at control-flow joins in forward direction):
 *   IN[B] = U OUT[P] for all predecessors P of B
 *
 * This is a "may" analysis with union merge because a definition reaches
 * a point if it MAY arrive along ANY path to that point.
 *)

module StringSet = Set.Make(String)
module StringMap = Map.Make(String)

(** A definition records where a variable is assigned.
    - [def_id]&#58;   unique label for this definition (e.g., "d1")
    - [var_name]&#58; the variable being defined (e.g., "a")
    - [block]&#58;    the basic block that contains this definition (e.g., "B1")
*)
type definition = {
  def_id : string;
  var_name : string;
  block : string;
}

(* compute_gen: Compute the gen set for a given block.
 *
 * The gen set contains the def_ids of definitions that are generated
 * (i.e., created) in this block. If a variable is defined multiple times
 * within the same block, only the LAST definition of that variable is
 * generated, because earlier definitions are immediately killed within
 * the block.
 *
 * @param defs   all definitions in the program
 * @param block  the label of the block to compute gen for
 * @return       StringSet of def_ids generated by this block
 *)
let compute_gen (defs : definition list) (block : string) : StringSet.t =
  let block_defs =
    List.filter (fun d -> d.block = block) defs
  in

  let last_defs =
    List.fold_left
      (fun acc def ->
        StringMap.add def.var_name def.def_id acc)
      StringMap.empty
      block_defs
  in

  StringMap.fold
    (fun _ def_id acc ->
      StringSet.add def_id acc)
    last_defs
    StringSet.empty

(* compute_kill: Compute the kill set for a given block.
 *
 * The kill set contains def_ids of definitions that are killed by this
 * block. A definition d_i of variable v is killed by block B if B
 * contains a definition of v AND d_i is not in gen[B].
 *
 * In other words: for each variable defined in block B, kill contains
 * all OTHER definitions of that variable (from any block).
 *
 * @param defs   all definitions in the program
 * @param block  the label of the block to compute kill for
 * @return       StringSet of def_ids killed by this block
 *)
let compute_kill (defs : definition list) (block : string) : StringSet.t =
  let gen_set =
    compute_gen defs block
  in

  let vars_defined_in_block =
    List.fold_left
      (fun acc def ->
        if def.block = block then
          StringSet.add def.var_name acc
        else
          acc)
      StringSet.empty
      defs
  in

  List.fold_left
    (fun acc def ->
      if StringSet.mem def.var_name vars_defined_in_block
         && not (StringSet.mem def.def_id gen_set)
      then
        StringSet.add def.def_id acc
      else
        acc)
    StringSet.empty
    defs

(* analyze: Run the reaching definitions forward iterative analysis.
 *
 * Given a CFG represented as (block_label, predecessor_labels) pairs and
 * a list of all definitions, compute the fixed-point solution.
 *
 * Algorithm:
 *   1. Initialize OUT[B] = {} for all blocks
 *   2. Repeat until no OUT set changes:
 *      a. For each block B:
 *         - IN[B]  = union of OUT[P] for all predecessors P of B
 *         - OUT[B] = gen[B] U (IN[B] - kill[B])
 *   3. Return (label, IN[B], OUT[B]) for each block
 *
 * @param cfg   list of (block_label, predecessor_labels) pairs
 * @param defs  all definitions in the program
 * @return      list of (block_label, in_set, out_set) triples
 *)
let analyze
    (cfg : (string * string list) list)
    (defs : definition list)
    : (string * StringSet.t * StringSet.t) list =

  let labels =
    List.map fst cfg
  in

  let empty_map =
    List.fold_left
      (fun acc label ->
        StringMap.add label StringSet.empty acc)
      StringMap.empty
      labels
  in

  let get_set label map =
    match StringMap.find_opt label map with
    | Some s -> s
    | None -> StringSet.empty
  in

  let union_predecessors preds out_map =
    List.fold_left
      (fun acc pred ->
        StringSet.union acc (get_set pred out_map))
      StringSet.empty
      preds
  in

  let rec iterate in_map out_map =
    let changed, new_in_map, new_out_map =
      List.fold_left
        (fun (changed, in_acc, out_acc) (label, preds) ->

          let old_out =
            get_set label out_acc
          in

          let in_set =
            union_predecessors preds out_acc
          in

          let gen_set =
            compute_gen defs label
          in

          let kill_set =
            compute_kill defs label
          in

          let out_set =
            StringSet.union
              gen_set
              (StringSet.diff in_set kill_set)
          in

          let changed =
            changed || not (StringSet.equal old_out out_set)
          in

          let in_acc =
            StringMap.add label in_set in_acc
          in

          let out_acc =
            StringMap.add label out_set out_acc
          in

          (changed, in_acc, out_acc))
        (false, in_map, out_map)
        cfg
    in

    if changed then
      iterate new_in_map new_out_map
    else
      (new_in_map, new_out_map)
  in

  let final_in_map, final_out_map =
    iterate empty_map empty_map
  in

  List.map
    (fun (label, _) ->
      let in_set =
        get_set label final_in_map
      in

      let out_set =
        get_set label final_out_map
      in

      (label, in_set, out_set))
    cfg